Repository Imageomics/kabr-tools, pull requests merged in 2024-10, with the labels that each got.

#51 Consolidate notebooks in single folder
  data/.gitignore
  notebooks/.gitignore
  notebooks/annotation_rescale.ipynb
  notebooks/time_budget.ipynb
  notebooks/train_yolo.ipynb
  src/.gitignore
Labels: documentation, structure

#36 33 update paths to scripts in readme
  .gitignore
  README.md
Labels: documentation

#42 Make video a parameter
  README.md
  src/kabr_tools/miniscene2behavior.py
Labels: structure

#53 updated documentation for annotation_rescale and downgrade.sh
  helper_scripts/downgrade.sh
  notebooks/annotation_rescale.ipynb
Labels: documentation
